/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gymp;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class MemberInfo extends javax.swing.JFrame {
private Connection con;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form MemberInfo
     */
    public MemberInfo() {
        initComponents();
        DisplayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member Info");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(200, 10, 650, 90);

        jTable1.setBackground(java.awt.Color.lightGray);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact", "Fee"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(480, 145, 610, 180);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(32, 145, 160, 39);
        jPanel2.add(id);
        id.setBounds(205, 152, 236, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Name:");
        jLabel3.setPreferredSize(new java.awt.Dimension(39, 29));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(32, 204, 160, 40);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name);
        name.setBounds(205, 204, 236, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Contact Info:");
        jLabel4.setPreferredSize(new java.awt.Dimension(39, 29));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(32, 262, 160, 40);
        jPanel2.add(contact);
        contact.setBounds(210, 270, 237, 35);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Fee:");
        jLabel5.setPreferredSize(new java.awt.Dimension(39, 29));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(32, 312, 160, 49);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1000");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(193, 324, 66, 34);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("3000");
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(263, 329, 75, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("5000");
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(342, 329, 80, 25);

        jButton1.setBackground(java.awt.Color.green);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Icon\\iconfinder_user_half_add_103774.png")); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(60, 400, 150, 60);

        jButton2.setBackground(java.awt.Color.green);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Icon\\iconfinder_search_298865.png")); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(230, 400, 150, 60);

        jButton7.setBackground(new java.awt.Color(16, 227, 17));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Icon\\iconfinder_refresh_326679.png")); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(420, 400, 150, 60);

        jButton5.setBackground(java.awt.Color.red);
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Icon\\iconfinder_delete_326606.png")); // NOI18N
        jButton5.setText("Delete");
        jButton5.setMaximumSize(new java.awt.Dimension(77, 25));
        jButton5.setMinimumSize(new java.awt.Dimension(77, 25));
        jButton5.setPreferredSize(new java.awt.Dimension(77, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(60, 490, 150, 60);

        jButton3.setBackground(java.awt.Color.green);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Icon\\iconfinder_renew_4168571.png")); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(230, 490, 150, 60);

        jButton8.setBackground(java.awt.Color.green);
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Icon\\iconfinder_back_126585.png")); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(420, 490, 150, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\c4e56e5d9c1e3bacb88b817026be8062.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 1140, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row=jTable1.getSelectedRow();
       id.setText(jTable1.getModel().getValueAt(row, 0).toString());
       name.setText(jTable1.getModel().getValueAt(row, 1).toString());
       contact.setText(jTable1.getModel().getValueAt(row, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.hide();
        AfterLogin l=new AfterLogin();
        l.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        id.setText(null);
        name.setText(null);
        contact.setText(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //Step-1: get a connection to the db
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/member",
                "root", "");
            String sql="delete from member where id=?";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            // pstmt.setInt(1,Integer.parseInt(t.getText()));
            pstmt.setString(1, id.getText());

            // JOptionPane.showMessageDialog(null, "Record deleted ");
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record deleted ");
            conn.close();
            DisplayTable();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //Step-1: get a connection to the db
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/member",
                "root", "");
            System.out.println("DB Connect Successful");
            //Step-2: create a statement
            String sql="update member set name=?,contact=?,fee=? where id=?";
            PreparedStatement pst=con.prepareStatement(sql);

            pst.setString(1, name.getText());
            pst.setString(2, contact.getText());
            String radioChoice = "";
            if(jRadioButton1.isSelected()){
                radioChoice = jRadioButton1.getText();
            }

            if(jRadioButton2.isSelected()){
                radioChoice = jRadioButton2.getText();
            }

            if(jRadioButton3.isSelected()){
                radioChoice = jRadioButton3.getText();
            }
            pst.setString(3, radioChoice);
            pst.setString(4,id.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Record Updated Successfully");
            con.close();
            DisplayTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //Step-1: get a connection to the db
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/member",
                "root", "");
            System.out.println("DB Connect Successful");
            //Step-2: create a statement
            String sql="select * from member where id=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,id.getText());
            ResultSet r=pst.executeQuery();
            if(r.next()){
                //
                name.setText(r.getString("name"));
                contact.setText(r.getString("contact"));
                /*jRadioButton1.setText(r.getString("fee"));
                jRadioButton2.setText(r.getString("fee"));
                jRadioButton3.setText(r.getString("fee"));*/
            }
            else{
                JOptionPane.showMessageDialog(null, "Record not Found!");
            }
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            //Step-1: get a connection to the db
            Connection con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/member",
                "root", "");
            System.out.println("DB Connect Successful");
            //Step-2: create a statement
            String sql="insert into member values(?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,id.getText());
            pst.setString(2, name.getText());
            pst.setString(3, contact.getText());
            String radioChoice = "";
            if(jRadioButton1.isSelected()){
                radioChoice = jRadioButton1.getText();
            }

            if(jRadioButton2.isSelected()){
                radioChoice = jRadioButton2.getText();
            }

            if(jRadioButton3.isSelected()){
                radioChoice = jRadioButton3.getText();
            }
            pst.setString(4, radioChoice);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Insert Successful");
            DisplayTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
    private void DisplayTable(){
       try{
           Class.forName("com.mysql.jdbc.Driver");
            //Step-1: get a connection to the db
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/member", 
                    "root", "");
            System.out.println("DB Connect Successful");
            String sql="select * from member";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
   }
    /*  public void insertMemberDB(ArrayList row) {
        try {
            String query = "insert into member(id,name,contact,fee) values('" +
                    row.get(0) + "','" + row.get(1) + "','" + row.get(2) +"','"+ row.get(3)+"');";
            System.out.println(query);
            //Step-3: Execute SQL query
           st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Member Info Added Successfully.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Insert into Database Exception: " + e);
            System.out.println(e);
        }
         
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
